CREATE TABLE IF NOT EXISTS BOOK
(
    BOOK_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(700) NOT NULL,
    AUTHOR_ID VARCHAR(500) NOT NULL,
    PUBLISHER VARCHAR(500) NOT NULL,
    QUANTITY BIGINT NOT NULL,
    PUBLICATION_DATE DATE NOT NULL
);
